name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    # environment: aws   # Ensure the "aws" environment is configured in GitHub with secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Use the latest version

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2  # Use the latest version
        with:
          terraform_version: 1.5.0  # Use the latest stable version of Terraform

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3  # Official AWS action for credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform changes
        run: terraform plan -out=tfplan

      - name: Apply Terraform changes
        run: terraform destroy --auto-approve
